on: push
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Update PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race ./...